"""Differentiable ODE integration via the continuous adjoint method.

`tangent.odeint(func, y0, ts, args)` integrates dy/dt = func(y, t, *args); its
gradient w.r.t. y0 and args is the adjoint method (tangent/ode.py), whose
adjoint dynamics are VJPs of the user's own `func` generated by tangent.vjp.
Gradients are checked against closed-form solutions and finite differences.
"""

import numpy as np
import pytest

import tangent
from tangent.errors import ForwardNotImplementedError, ReverseNotImplementedError


# --- Dynamics (module level so their source is retrievable). ---


def linear(y, t, k):
    return -k * y


def pendulum(y, t, k, c):
    return np.array([y[1], -k * np.sin(y[0]) - c * y[1]])


def spiral(y, t):
    return np.array([-0.1 * y[0] - y[1], y[0] - 0.1 * y[1]])


# --- Losses. ---


def linear_final_loss(y0, k):
    ts = np.array([0.0, 0.5, 1.0])
    ys = tangent.odeint(linear, y0, ts, (k,))
    return np.sum(ys[-1])


def linear_traj_loss(y0, k):
    ts = np.linspace(0.0, 1.0, 4)
    ys = tangent.odeint(linear, y0, ts, (k,))
    return np.sum(ys**2)


def pendulum_loss(y0, k, c):
    ts = np.linspace(0.0, 2.0, 5)
    ys = tangent.odeint(pendulum, y0, ts, (k, c))
    return np.sum(ys[-1] ** 2)


def spiral_loss(y0):
    ts = np.linspace(0.0, 3.0, 6)
    ys = tangent.odeint(spiral, y0, ts, ())
    return np.sum(ys**2)


def _fd(f, args, i, eps=1e-6):
    """Central finite-difference gradient of scalar f w.r.t. args[i]."""
    a = args[i]
    if np.isscalar(a):
        ap, am = list(args), list(args)
        ap[i], am[i] = a + eps, a - eps
        return (f(*ap) - f(*am)) / (2 * eps)
    g = np.zeros_like(np.asarray(a, dtype=float))
    for j in range(g.size):
        ap = [np.array(x, dtype=float) if not np.isscalar(x) else x for x in args]
        am = [np.array(x, dtype=float) if not np.isscalar(x) else x for x in args]
        ap[i].ravel()[j] += eps
        am[i].ravel()[j] -= eps
        g.ravel()[j] = (f(*ap) - f(*am)) / (2 * eps)
    return g


class TestClosedForm:
    def test_forward_matches_analytic(self):
        # y(t) = y0 * exp(-k t)
        from tangent import ode

        y0 = np.array([2.0, 1.0])
        ys = ode.odeint(linear, y0, np.array([0.0, 1.0]), (0.5,))
        np.testing.assert_allclose(ys[-1], y0 * np.exp(-0.5), rtol=1e-5)

    def test_grad_y0_analytic(self):
        # d/dy0 sum(y(T)) = exp(-kT)
        g = tangent.grad(linear_final_loss, wrt=(0,))(np.array([2.0, 1.0]), 0.5)
        np.testing.assert_allclose(g, np.exp(-0.5) * np.ones(2), rtol=1e-4)

    def test_grad_param_analytic(self):
        # d/dk sum(y(T)) = -T y0 exp(-kT)
        y0 = np.array([2.0, 1.0])
        g = tangent.grad(linear_final_loss, wrt=(1,))(y0, 0.5)
        assert g == pytest.approx(np.sum(-1.0 * y0 * np.exp(-0.5)), rel=1e-4)


class TestFiniteDifference:
    @pytest.mark.parametrize('i', [0, 1, 2], ids=['y0', 'k', 'c'])
    def test_pendulum(self, i):
        args = (np.array([0.5, 0.0]), 3.0, 0.3)
        g = tangent.grad(pendulum_loss, wrt=(i,))(*args)
        np.testing.assert_allclose(g, _fd(pendulum_loss, args, i), rtol=2e-3, atol=1e-4)

    def test_autonomous_no_args(self):
        y0 = np.array([1.0, 0.5])
        g = tangent.grad(spiral_loss)(y0)
        np.testing.assert_allclose(g, _fd(spiral_loss, [y0], 0), rtol=2e-3, atol=1e-4)

    def test_trajectory_loss(self):
        # Cotangents land at every output time, not just the last.
        y0 = np.array([1.5])
        g = tangent.grad(linear_traj_loss, wrt=(0,))(y0, 0.4)
        np.testing.assert_allclose(g, _fd(linear_traj_loss, [y0, 0.4], 0), rtol=2e-3, atol=1e-4)


class TestConstantMemory:
    def test_gradient_independent_of_step_count(self):
        # The adjoint method's answer must not drift with the number of RK4
        # sub-steps (only its accuracy improves), and memory stays flat.
        from tangent import ode

        y0 = np.array([1.0, -0.5])
        ts = np.array([0.0, 1.0])

        def loss(steps):
            ys = ode.odeint(pendulum, y0, ts, (2.0, 0.2), num_steps=steps)
            dys = np.zeros_like(ys)
            dys[-1] = 1.0
            gy0, gargs = ode.odeint_grad(dys, pendulum, ys, y0, ts, (2.0, 0.2), num_steps=steps)
            return gy0

        g10 = loss(10)
        g80 = loss(80)
        np.testing.assert_allclose(g10, g80, rtol=1e-3)


class TestCleanFailures:
    def test_forward_mode_not_implemented(self):
        with pytest.raises(ForwardNotImplementedError):
            tangent.autodiff(linear_final_loss, mode='forward')(np.array([1.0]), 0.5)

    def test_higher_order_not_implemented(self):
        with pytest.raises(ReverseNotImplementedError):
            tangent.grad(tangent.grad(linear_final_loss))(np.array([1.0]), 0.5)
