"""Differentiable ODE integration with Tangent's adjoint-method odeint.

Fit the decay rate of dy/dt = -k y from a single observation, by gradient
descent on k through `tangent.odeint`. The gradient of the loss w.r.t. k flows
through the ODE solve via the continuous adjoint method - and the adjoint
dynamics are the vector-Jacobian product of `dynamics` below, generated by
Tangent itself.

    python examples/neural_ode.py
"""

import numpy as np

import tangent


def dynamics(y, t, k):
    """dy/dt = -k y."""
    return -k * y


def loss(k):
    y0 = np.array([2.0])
    ts = np.array([0.0, 1.0])
    ys = tangent.odeint(dynamics, y0, ts, (k,))
    target = 2.0 * np.exp(-0.7 * 1.0)  # observation generated with the true k=0.7
    return float((ys[-1, 0] - target) ** 2)


def main():
    dloss_dk = tangent.grad(loss)

    k = 0.1  # start far from the truth
    lr = 0.5
    print('fitting dy/dt = -k y  (true k = 0.7)')
    for step in range(25):
        g = dloss_dk(k)
        k = k - lr * g
        if step % 5 == 0 or step == 24:
            print('  step %2d   k = %.4f   loss = %.3e' % (step, k, loss(k)))
    print('recovered k = %.4f' % k)


if __name__ == '__main__':
    main()
